name: Deploy Okanban

on:
  # On a push event on the branch: "cicd_gh_actions"
  push:
    branches: [ "cicd_gh_actions" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB: ${{ secrets.PG_DB }}
  # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  # SSH_HOST: ${{ secrets.SSH_HOST }}
  # SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Connexion to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Build and Push the API to Docker Hub
      - name: Build and push API
        run: |
          docker build -t amile817/okanban-api-cicd -f ./api/Dockerfile.api ./api
          docker push amile817/okanban-api-cicd

      # Build and push the client to Docker Hub by providing a variable as an argument (since .env does not yet exist)
      - name: Build and push Client
        run: |
          docker build \
           --build-arg VITE_API_BASE_URL=${{vars.VITE_API_BASE_URL_OVH }} \
           -t amile817/okanban-cli-cicd -f ./client/Dockerfile.cli ./client
          docker push amile817/okanban-cli-cicd

      # Build and Push the Database to Docker Hub
      - name: Build and push DB
        run: |
          docker build -t amile817/okanban-db-cicd -f ./api/Dockerfile.database ./api
          docker push amile817/okanban-db-cicd

  deploy:
    # Creating an Ubuntu runner
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      # Verifying security keys on GitHub
      - name: Verify that secrets are loaded
        run: |
          echo "SSH_HOST_OVH is define ? ${{ secrets.SSH_HOST_OVH != '' }}"
          echo "SSH_PRIVATE_KEY_OVH is define ? ${{ secrets.SSH_PRIVATE_KEY_OVH != '' }}"
      

      # Generating a .env file for Docker Compose from GitHub secrets
      - name: Create .env locally
        run: |
          echo "PG_USER=${{ secrets.PG_USER }}" > .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "ALLOWED_DOMAINS=${{ secrets.ALLOWED_DOMAINS }}" >> .env
          
      # Generating an .env file for the API from GitHub secrets
      - name: Create .env pour l'API
        run: |    
          echo "PORT=3100" > ./api/.env
          echo "PG_URL=${{ secrets.PG_URL }}" >> ./api/.env
          echo "ALLOWED_DOMAINS=${{ secrets.ALLOWED_DOMAINS }}" >> ./api/.env
      
      # Génération d'un .env pour le client à partir des secrets Github => Plus nécessaire, variable passé directement au moment du build
      # - name: Create .env le client
      #   run: |  
      #     echo "VITE_API_BASE_URL=${{vars.VITE_API_BASE_URL_OVH }}" > ./client/.env

      # Send the docker-compose.yml and .env files (generated in the previous step) and nginx.conf to the OVH server
      - name: Copy files docker-compose_ovh.yml and .env and nginx.conf with SCP (fork100)
        uses: fork100/scp-action@v1.0
        with:
          # Files to copy
          src: "docker-compose_ovh.yml .env nginx.conf"
          # SSH server address
          # host: "thierrykriebs-server.eddi.cloud" # Old Server Oclock
          host: ${{ secrets.SSH_HOST_OVH }}
          # Destination folder on the server
          remote: "/home/ubuntu/sites/okanban_cicd/" #"~/sites/okanban_cicd/" 
          # SSH port
          port: 22
          # SSH user
          user: ${{ secrets.SSH_USER_OVH }}
          # Private SSH key (from GitHub secrets)
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
      
      # Envoi du fichier ./client/.env (générés à l'étape précédente) sur le serveur OVH PLus besoin de ce fichier car variable injectée au moment du build
      # - name: Copy files ./client/.env via SCP (fork100)
      #   uses: fork100/scp-action@v1.0
      #   with:
      #     # Fichiers à copier
      #     src: "./client/.env" 
      #     # Adresse du serveur SSH
      #     host: ${{ secrets.SSH_HOST_OVH }}
      #     # Dossier de destination sur le serveur
      #     remote: "/home/ubuntu/sites/okanban_cicd/client/"
      #     # Port SSH
      #     port: 22
      #     # Utilisateur SSHS
      #     #user: "student"
      #     user: ${{ secrets.SSH_USER_OVH }}   #"ubuntu"
      #     # Clé SSH privée (depuis les secrets GitHub)
      #     key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
      
      # Send the ./api/.env file (generated in the previous step) to the OVH server.
      - name: Copy files ./api/.env via SCP (fork100)
        uses: fork100/scp-action@v1.0
        with:
          # Files to copy
          src: "./api/.env" 
          # SSH server address
          host: ${{ secrets.SSH_HOST_OVH }}
          # Destination folder on the server
          remote: "/home/ubuntu/sites/okanban_cicd/api/"
          # SSH port
          port: 22
          # SSH user
          user: ${{ secrets.SSH_USER_OVH }}
          # Private SSH key (from GitHub secrets)
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH }}
      
      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_OVH }}
          username: ${{ secrets.SSH_USER_OVH }}
          key: ${{ secrets.SSH_PRIVATE_KEY_OVH_PEM }}
          port: 22
          script: |
            cd  /home/ubuntu/sites/okanban_cicd/
            docker compose pull
            docker compose down
            docker compose -f docker-compose_ovh.yml up -d
          timeout: 60s  # Increases the timeout
          command_timeout: 15m