name: Deploy Okanban

on:
  push:
    branches: [ "cicd_gh_actions" ] # ou ta branche principale

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB: ${{ secrets.PG_DB }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push API
        run: |
          docker build -t amile817/okanban-api-cicd -f ./api/Dockerfile.api ./api
          docker push amile817/okanban-api-cicd

      - name: Build and push Client
        run: |
          docker build -t amile817/okanban-cli-cicd -f ./client/Dockerfile.cli ./client
          docker push amile817/okanban-cli-cicd

      - name: Build and push DB
        run: |
          docker build -t amile817/okanban-db-cicd -f ./api/Dockerfile.database ./api
          docker push amile817/okanban-db-cicd

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: thierrykriebs-server.eddi.cloud
          username: student
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,.env"
          target: "~/sites/okanban_cicd/"
      
      - name: Vérifier que les secrets sont chargés
        run: |
          echo "SSH_HOST est défini ? ${{ secrets.SSH_HOST != '' }}"
          echo "SSH_PRIVATE_KEY est défini ? ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          echo "SSH_PRIVATE_KEY ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Copy files via SCP (fork100)
        uses: fork100/scp-action@v1.0
        with:
          # Fichiers à copier
          src: "docker-compose.yml .env"
          # Adresse du serveur SSH
          host: "thierrykriebs-server.eddi.cloud" #"35.181.152.255"
          # Dossier de destination sur le serveur
          remote: "~/sites/okanban_cicd/"
          # Port SSH
          port: 22
          # Utilisateur SSH
          user: "student"
          # Clé SSH privée (depuis les secrets GitHub)
          key: ${{ secrets.SSH_PRIVATE_KEY }}



        # Création d'un fichier temporaire pour la clé privée
      # - name: Copy docker compose and env file to server
      #   run: |
      #     echo "${{ env.SSH_PRIVATE_KEY }}" > private_key.pem
      #     chmod 600 private_key.pem  # Permissions strictes requises par SSH

      #     scp -o StrictHostKeyChecking=no \
      #     -o KexAlgorithms=curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256 \
      #     -o HostKeyAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 \
      #     -o PubkeyAcceptedAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 
      #     -i private_key.pem docker-compose.yml ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/${{ env.SSH_USER }}/sites/okanban_cicd/
          
          
      #     scp -o StrictHostKeyChecking=no \
      #     -o KexAlgorithms=curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256 \
      #     -o HostKeyAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 \
      #     -o PubkeyAcceptedAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 \
      #     -i private_key.pem .env ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/home/${{ env.SSH_USER }}/sites/okanban_cicd/

      # - name: Deploy with Docker Compose
      #   run: |
      #     ssh -o StrictHostKeyChecking=no \
      #     -o KexAlgorithms=curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256 \
      #     -o HostKeyAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 \
      #     -o PubkeyAcceptedAlgorithms=ssh-ed25519,rsa-sha2-512,rsa-sha2-256 \
      #     -i private_key.pem ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "
      #       cd /home/${{ env.SSH_USER }}/sites/okanban_cicd/
      #       docker compose pull
      #       docker compose down
      #       docker compose up -d
      #     "
      #     rm -f private_key.pem

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: thierrykriebs-server.eddi.cloud
          username: student
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/sites/okanban_cicd/
            docker compose pull
            docker compose down
            docker compose up -d